# until https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6678
m2w64_c_stdlib:             # [win]
  - m2w64-sysroot           # [win]
m2w64_c_stdlib_version:     # [win]
  - 12                      # [win]

ROCM_COMPILATION:
  - "enabled"
  - "disabled"
