{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.2.0" %}
{% set sha256 = "2defba03ddd91761b858cbbdc2e3a6e27b44e94696dbfa21380191328485a433" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pname }}-{{ version }}.tar.gz
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config                # [unix]
    - posix                     # [win]
    - clangdev                  # [win]
    - llvmdev                   # [win]
    - lld                       # [win]
    - m2-perl                   # [win]
    - m2-automake-wrapper       # [win]
    - m2-libtool                # [win]
    - m2-autoconf               # [win]
    - m2-make                   # [win]
    - m2-m4                     # [win]
    - python >3                 # [win]
    - make                      # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - autoconf                  # [unix]
  host:
    - libxml2
    - pthreads-win32            # [win]
  run:
    - libxml2
    - pthreads-win32            # [win]

test:
  commands:
    - hwloc-ls

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD 3-Clause
  license_file: COPYING
  summary: Portable Hardware Locality (hwloc)

extra:
  recipe-maintainers:
    - inducer
    - isuruf
