{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.9.1" %}
{% set sha256 = "a440e2299f7451dc10a57ddbfa3f116c2a6c4be1bb97c663edd3b9c7b3b3b4cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win and vc<14]
  skip: true  # [cuda_compiler_version != "None" and win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
    - pkg-config                # [unix]
    - autotools_clang_conda     # [win]
    - make                      # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - autoconf                  # [unix]
  host:
    - libxml2
    - pthreads-win32            # [win]
  run:
    - libxml2
    - pthreads-win32            # [win]
    - __cuda                    # [cuda_compiler_version != "None"]

test:
  commands:
    - hwloc-ls                                     # [cuda_compiler_version == "None"]
    - test -f ${PREFIX}/lib/libhwloc${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_LIB%\hwloc.lib exit 1  # [win]

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD-3-Clause
  license_file: COPYING
  summary: Portable Hardware Locality (hwloc)

extra:
  recipe-maintainers:
    - jan-janssen
    - inducer
    - isuruf
