{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.11.2" %}
{% set sha256 = "866ac8ef07b350a6a2ba0c6826c37d78e8994dcbcd443bdd2b436350de19d540" %}
{% set build = 1 %}

{% if cuda_compiler_version == "None" and ROCM_COMPILATION == "disabled" %}
{% set build = build + 1000 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # backport https://github.com/open-mpi/hwloc/pull/632
    - patches/0001-utils-lstopo-don-t-build-lstopo-win-with-MSVC.patch

build:
  number: {{ build }}
  skip: true  # [cuda_compiler_version != "None" and win]
  skip: true  # [cuda_compiler_version != "None" and ROCM_COMPILATION == "enabled"]
  skip: true  # [not linux64 and ROCM_COMPILATION == "enabled"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: rocm_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [ROCM_COMPILATION == "enabled"]
  string: default_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None" and ROCM_COMPILATION == "disabled"]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}
  # weigh down gpu implementation and give nocuda preference
  track_features:
    - cudatoolkit               # [cuda_compiler_version != "None"]
    - rocm                      # [ROCM_COMPILATION == "enabled"]

requirements:
  build:
    - {{ stdlib('c') }}         # [unix]
    - {{ stdlib('m2w64_c') }}   # [win]
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
    - pkg-config                # [unix]
    - autotools_clang_conda     # [win]
    - make                      # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - autoconf                  # [unix]
  host:
    - libxml2
    - winpthreads-devel         # [win]
    - rocm-smi                  # [linux and cuda_compiler_version == "None" and ROCM_COMPILATION == "enabled"]
  run:
    - __cuda                    # [cuda_compiler_version != "None"]

test:
  commands:
    - hwloc-ls                                     # [cuda_compiler_version == "None"]
    - test -f ${PREFIX}/lib/libhwloc${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_LIB%\hwloc.lib exit 1  # [win]

about:
  home: https://www.open-mpi.org/projects/hwloc/
  dev_url: https://github.com/open-mpi/hwloc
  license: BSD-3-Clause
  license_file: COPYING
  summary: Portable Hardware Locality (hwloc)
  description: |
    This feedstock builds the hwloc library in the `libhwloc` conda package. Different variants of the package are built:
    * `default` in the build string: Without CUDA or ROCM support, installed by default. Install specifically this version with `conda install libhwloc=*=*default*`.
    * `cuda` in the build string: With CUDA support. Install specifically this version with  `conda install libhwloc=*=*cuda*`
    * `rocm` in the build string: With ROCM support. Install specifically this version with  `conda install libhwloc=*=*rocm*`

extra:
  recipe-maintainers:
    - jan-janssen
    - inducer
    - isuruf
