{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.9.2" %}
{% set sha256 = "ffb554d5735e0e0a19d1fd4b2b86e771d3b58b2d97f257eedacae67ade5054b3" %}
{% set build_num = 8 %}

{% if cuda_compiler_version == "None" %}
{% set build_num = build_num + 1000 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_num }}
  skip: true  # [win and vc<14]
  skip: true  # [cuda_compiler_version != "None" and win]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: nocuda_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}
  # weigh down gpu implementation and give nocuda preference
  track_features:
    - cudatoolkit               # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
    - pkg-config                # [unix]
    - autotools_clang_conda     # [win]
    - make                      # [unix]
    - automake                  # [unix]
    - libtool                   # [unix]
    - autoconf                  # [unix]
  host:
    - libxml2
    - pthreads-win32            # [win]
  run:
    - libxml2
    - pthreads-win32            # [win]
    - __cuda                    # [cuda_compiler_version != "None"]

test:
  commands:
    - hwloc-ls                                     # [cuda_compiler_version == "None"]
    - test -f ${PREFIX}/lib/libhwloc${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_LIB%\hwloc.lib exit 1  # [win]

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD-3-Clause
  license_file: COPYING
  summary: Portable Hardware Locality (hwloc)

extra:
  recipe-maintainers:
    - jan-janssen
    - inducer
    - isuruf
