provider:
  linux_ppc64le: default
  linux_aarch64: default
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: A4for0evHe19MIe10Ah8k2hhIYXK1IiCYM91f/WaKYKSly4BSoYGRh0Sb9hxiiChSjeQL5dkodMdHXSEHMvz9EaKJL2SsKaOL6Hc4z9arOR6+XEklhlT2MwYBH+DlyQYmFAu5Zc3KgH8yy7AEl6s92Wo+CvpNBI+IALuiumECYJxBhDyodquPT8WOZvZ+PxJx78rdopbQ1nsAp5lqX1RIcBEDRlw8EsnBu0RSkyYFK+uSbe6xH0yhOTSbBJbBjRC9FUPbabPZA4IWpOjFZAUzI0iDbjwImBOB/fLox6vK2GM/jur/KJ0ftMd70fUV3QbOQTQTuSRkfXeh+x6rh2RTDhiqey+lWLA3WGl6+UY1S1AApoRx4fSLdnfvnRaw+oAOsps3P+9v/KxYrzzuAPlMjkf3xpnvJ2zDG7f1hs1jJvmsI5MbmW6n29HEkBGjmOlYth4/yXJCLRWTeZ9C8Hfx18aoFwTYw8rDWdxtekKtWfT2v9+vll5/wO7LEAawiIdaAiJOyIKjPRsXokV6beZsOUoEQI0asvhxz/g+RQSMUNbCMjyqF6arlslrKdnudYSrRwQdmtPDKsNx5RyW02WH1jaAscVKWBOMjSvx3+aKylIi0LzQCB95/MAmnYopjr6hrD3wsM1j0zXn2JfQNn+1IP/0+6cJhEj2F6cuA5QK2U=}
conda_forge_output_validation: true
